// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'OrganismsGlobalFooter': typeof import('../components/organisms/GlobalFooter.vue')['default'],
    'OrganismsGlobalHeader': typeof import('../components/organisms/GlobalHeader.vue')['default'],
    'OrganismsMemberDetailExperience': typeof import('../components/organisms/MemberDetailExperience.vue')['default'],
    'OrganismsMemberDetailSelfIntroduction': typeof import('../components/organisms/MemberDetailSelfIntroduction.vue')['default'],
    'OrganismsMemberDetailSkills': typeof import('../components/organisms/MemberDetailSkills.vue')['default']
  }
}
export {}
